-- Migration 005 UP: allow system-generated documents
-- The auto-pipeline (WhatsApp PO -> extract -> generate) has no human
-- operator, so generated_by becomes nullable. NULL = generated by the
-- system; the audit row still records generator version, source-data
-- snapshot, and output hash.

alter table public.generated_documents
  alter column generated_by drop not null;
